#!/bin/bash

cd /usr/share/pixmaps
ls -1 background{1..9} > /dev/null 2>&1	  
if [ "$?" = "0" ]; then #If 'ls' status is 0 (there are backgrounds in the folder)...
    for (( i=1; i<=9; i++ )); do
	#...sets the next wallpaper in the list as the current one.
	if [ -f background$i.jpg ]; then
	    mv background$i.jpg background.jpg
	    break
	fi
    done
else    
    #Keeps the script working until a network connection is detected.
    ping -c 1 wallhaven.cc
    while [[ $? != 0 ]]; do	
	ping -c 1 wallhaven.cc
    done
    #Creates a library consisting of 10 wallpapers for local use.
    rm background.jpg #We want to spend the less time possible without a wallpaper, so we wait until now to remove it.
    for (( i=0; i<10; i++ )); do
	until [ -f background$i.jpg ]; do
	    WALLNUMBER=$((1 + RANDOM % 484214))
	    sudo wget https://wallpapers.wallhaven.cc/wallpapers/full/wallhaven-$WALLNUMBER.jpg
	    sudo mv wallhaven-$WALLNUMBER.jpg background$i.jpg
	done
    done
    #Sets and locks wallpaper for an hour.
    for (( i=0; i<10; i++ )); do
	mv background$i.jpg background.jpg
	sleep 1h
    done
fi
