#!/bin/bash

#If exists any background other than background.jpg, change it and exit so as not to repeat backgrounds if the sleep time is not completed.
cd /usr/share/pixmaps
#Is there any background[number].jpg file in the folder?
ls -1 background{1..9} > /dev/null 2>&1
if [ "$?" = "0" ]; then
    for (( i=1; i<=9; i++ )); do
	#If backgroundX.jpg exists, set it as the main wallpaper. This will always be the one which follows the current one.
	if [ -f background$i.jpg ]; then
	    mv background$i.jpg background.jpg
	    break
	fi
    done
else    
    #Keeps the script working until a network connection is detected.
    ping -c 1 wallhaven.cc
    while [[ $? != 0 ]]; do	
	ping -c 1 wallhaven.cc
    done
    #Creates a library consisting of 10 wallpapers for local use.
    rm background.jpg #Check!!!
    for (( i=0; i<10; i++ )); do
	until [ -f background$i.jpg ]; do
	    WALLNUMBER=$((1 + RANDOM % 484214))
	    sudo wget https://wallpapers.wallhaven.cc/wallpapers/full/wallhaven-$WALLNUMBER.jpg
	    sudo mv wallhaven-$WALLNUMBER.jpg background$i.jpg
	done
    done
    #Sets and locks wallpaper for two hours.
    #When powering off the computer, I want to change to the next wallpaper.
    for (( i=0; i<10; i++ )); do
	mv background$i.jpg background.jpg
	sleep 15s
    done
fi
